apiVersion: v1
kind: Service
metadata:
  name: zerobig-cockpit
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 9090
    nodePort: 30003
    targetPort: 9090
  selector:
    name: zerobig-cockpit
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zerobig-cockpit
spec:
  template:
    metadata:
      labels:
        name: zerobig-cockpit
    spec:
      containers:
      - name: cockpit
        image: cockpit/kubernetes:latest 
        ports:
        - containerPort: 9090
          protocol: TCP
